### PR TITLE
Pre-release fixes for 0.2.0

### PR DESCRIPTION
**Pull request by aditya7iyengar**

### CODE REVIEW

**Comment by aeturnumfluctus** [comment]
@aditya7iyengar @ericsullivan 

I think there's a mistake in the documentation for `Akd.Fetch.Git.uniq_merge`:

[Here](https://github.com/annkissam/akd/blob/86bca7d63e618cf3ac7f46b5e23007f8e7521446/lib/akd/base/fetch/git.ex#L110), the following is stated:

```elixir
  # the first value of keyword1 corresponding to that key.
```
however, according to the docs for `Keyword.new(pairs)`([here](https://hexdocs.pm/elixir/Keyword.html#new/2)), "[d]uplicated entries are removed, the latest one prevails."

**Comment by aditya7iyengar** [comment]
Yup, Good catch!
I think we can change the documentation!

**Comment by aditya7iyengar** [comment]
@ericsullivan The last commit should take care of local builds. Now do you think we can move to building these applications locally?

**Comment by aditya7iyengar** [comment]
@aeturnumfluctus If we could extract the `uniq_merge` to the `__using__` macros in `Akd.Hook` and `Akd.Task` that would also reduce the duplication.

**Comment by ericsullivan** [comment]
@aditya7iyengar Why do you want to build locally? I mean, you can, but I prefer the build server approach.

**Comment by ericsullivan** [comment]
@aditya7iyengar is this ready to release?

**Pull request merged**
